// @ts-check
/**
 * Rehype plugin that turns each block-level image in rendered markdown into a
 * captioned, lazily loaded figure, serving the gist screenshots through
 * `<picture>` with lighter WebP copies when they exist:
 *
 *   #### Home Page
 *   <img alt="Screenshot 2026-08-31 080518" src="/prd/mocks/01-home-page.png" />
 *
 * becomes (first figure on the page; later ones get `loading="lazy"` and no
 * `fetchpriority`)
 *
 *   <h4>Home Page</h4>
 *   <figure class="figure">
 *     <picture>
 *       <source type="image/webp"
 *               srcset="/prd/mocks/derived/01-home-page-760.webp 760w, /prd/mocks/derived/01-home-page-1320.webp 1320w"
 *               sizes="(min-width: 48em) 658px, calc(100vw - 2rem)">
 *       <img alt="Home Page" src="/prd/mocks/01-home-page.png" loading="eager" fetchpriority="high" decoding="async" />
 *     </picture>
 *     <figcaption>Home Page</figcaption>
 *   </figure>
 *
 * The `<img>` keeps its PNG `src`, alt, `loading` and `decoding`, so selectors,
 * captions, print and accessibility checks see the same element; the browser
 * swaps in the WebP from `<source>` when it can. The WebP copies live in
 * `public/mocks/derived/` and are generated by `scripts/make-mocks.mjs` before
 * every build (`prebuild`/`predev`); an image whose two copies are missing, or
 * whose `src` is not under `…/mocks/`, is emitted as a plain `<img>`.
 *
 * The caption is the text of the nearest preceding `h4`; a higher heading
 * (h1–h3) starts a new section and clears it, so an image with no h4 of its own
 * gets a figure without a caption. When there is a caption and the image's own
 * alt is a placeholder — missing, blank, the file name, or an auto-generated
 * "Screenshot 2026-08-31 080518" — the caption becomes the alt, so a screen
 * reader hears what the screenshot shows; a written alt is never replaced.
 * Only top-level images are wrapped: a raw
 * `<img>` HTML block (the gist's screenshots) or a paragraph whose only content
 * is an `<img>` (markdown `![alt](src)` syntax). Inline images inside text and
 * every other node are left alone, so the document text does not change.
 *
 * Astro runs user rehype plugins before rehype-raw, so the gist's `<img>` tags
 * are still `raw` string nodes here; they are edited as strings and become
 * elements when rehype-raw parses the tree.
 *
 * @typedef {{
 *   type: string,
 *   tagName?: string,
 *   value?: string,
 *   properties?: Record<string, unknown>,
 *   children?: HastNode[],
 * }} HastNode
 *
 * @typedef {(publicPath: string) => boolean} Exists
 *   Whether `public/<publicPath>` exists (`mocks/derived/01-home-page-760.webp`).
 *
 * @typedef {{ exists?: Exists }} FigureOptions
 */

import { existsSync } from 'node:fs';
import path from 'node:path';

/** A raw HTML block that is exactly one `<img …>` tag (surrounding whitespace allowed). */
const RAW_IMG_BLOCK = /^\s*<img\b[^>]*>\s*$/i;
const CAPTION_TAGS = new Set(['h4']);
const SECTION_TAGS = new Set(['h1', 'h2', 'h3']);
/** `alt="…"` / `alt='…'` / bare `alt` on a raw `<img>` tag. */
const RAW_ALT = /\salt(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'>]+)))?/i;
const RAW_SRC = /\ssrc\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'>]+))/i;
const IMAGE_EXTENSION = /\.(?:png|jpe?g|gif|webp|svg|avif|bmp)$/i;
/** Auto-generated screenshot names such as GitHub's "Screenshot 2026-08-31 080518". */
const SCREENSHOT_NAME = /^screen ?shot\b[\s\d:._-]*(?:at[\s\d:._-]*)?(?:[ap]m)?$/i;
/** A gist screenshot: `<prefix>/mocks/<stem>.png`, the prefix being the site base applied by rehype-base. */
const MOCK_SRC = /^(?<prefix>.*)\/mocks\/(?<stem>[^/]+)\.png$/i;

/** Widths of the derived WebP copies (see scripts/make-mocks.mjs). */
export const DERIVED_WIDTHS = [760, 1320];

/**
 * How wide a screenshot renders, for `<source sizes>`: the content column caps
 * at ≈658 CSS px from 48em up; below that the figure fills the viewport minus
 * the page padding. A phone at DPR 2 and a desktop at DPR 1 pick the 760w copy,
 * a desktop at DPR 2 the 1320w one.
 */
export const SIZES = '(min-width: 48em) 658px, calc(100vw - 2rem)';

/**
 * Default `exists`: looks under `public/` of the current working directory
 * (Astro runs the markdown pipeline from the project root).
 * @type {Exists}
 */
export function publicFileExists(publicPath) {
  return existsSync(path.resolve(process.cwd(), 'public', publicPath));
}

/**
 * The derived WebP copies of a mock screenshot: `public/`-relative paths and
 * the URLs they are served from, or undefined when `src` is not a mock PNG.
 * @param {string | undefined} src
 * @returns {{ files: string[], urls: string[] } | undefined}
 */
function derivedCopies(src) {
  const match = MOCK_SRC.exec(src ?? '');
  if (!match?.groups) return undefined;
  const { prefix, stem } = match.groups;
  const names = DERIVED_WIDTHS.map((width) => `${stem}-${width}.webp`);
  return {
    files: names.map((name) => `mocks/derived/${name}`),
    urls: names.map((name) => `${prefix}/mocks/derived/${name}`),
  };
}

/**
 * The `srcset` for a mock screenshot's WebP copies, or undefined when it is not
 * a mock PNG or one of the copies is missing.
 * @param {string | undefined} src
 * @param {Exists} exists
 * @returns {string | undefined}
 */
function webpSrcset(src, exists) {
  const copies = derivedCopies(src);
  if (!copies || !copies.files.every((file) => exists(file))) return undefined;
  return copies.urls.map((url, i) => `${url} ${DERIVED_WIDTHS[i]}w`).join(', ');
}

/**
 * True when an image's alt text says nothing a caption would not say better:
 * missing, blank, the file name (with or without its extension), or an
 * auto-generated screenshot name. A written alt is never touched.
 * @param {string | undefined} alt
 * @param {string | undefined} src
 * @returns {boolean}
 */
export function isPlaceholderAlt(alt, src) {
  const text = (alt ?? '').trim();
  if (!text) return true;
  if (IMAGE_EXTENSION.test(text) || SCREENSHOT_NAME.test(text)) return true;
  const file = (src ?? '').split(/[?#]/)[0].split('/').pop() ?? '';
  const stem = file.replace(IMAGE_EXTENSION, '');
  const lower = text.toLowerCase();
  return file !== '' && (lower === file.toLowerCase() || lower === stem.toLowerCase());
}

/**
 * Concatenates the text of a node's descendants.
 * @param {HastNode} node
 * @returns {string}
 */
export function textOf(node) {
  if (node.type === 'text') return node.value ?? '';
  return (node.children ?? []).map(textOf).join('');
}

/** `loading="…"` / `fetchpriority="…"` attributes on a raw `<img>` tag, for replacing. */
const RAW_LOADING = /\sloading\s*=\s*(?:"[^"]*"|'[^']*'|[^\s"'>]+)/gi;
const RAW_FETCHPRIORITY = /\sfetchpriority\s*=\s*(?:"[^"]*"|'[^']*'|[^\s"'>]+)/gi;

/**
 * Adds `loading="lazy"` and `decoding="async"` to a raw `<img …>` tag string,
 * keeping any values the tag already carries. With `eager` (the first figure on
 * the page, the likely LCP element) it emits `loading="eager"` and
 * `fetchpriority="high"` instead, replacing an existing `loading`.
 * @param {string} tag
 * @param {{ eager?: boolean }} [options]
 * @returns {string}
 */
export function lazyImgTag(tag, { eager = false } = {}) {
  let out = tag;
  const wanted = eager
    ? ['loading="eager"', 'fetchpriority="high"', 'decoding="async"']
    : ['loading="lazy"', 'decoding="async"'];
  if (eager) out = out.replace(RAW_LOADING, '').replace(RAW_FETCHPRIORITY, '');
  const missing = wanted.filter((attr) => !new RegExp(`\\s${attr.split('=')[0]}=`, 'i').test(out));
  if (missing.length === 0) return out;
  // Insert before the closing `/>` or `>`.
  out = out.replace(/\s*\/?>\s*$/, (end) => ` ${missing.join(' ')}${end.trimStart() === '/>' ? ' />' : '>'}`);
  return out;
}

/**
 * Wraps a raw `<img …>` tag string whose `src` is a mock screenshot
 * (`<prefix>/mocks/<stem>.png`) in a `<picture>` that offers the derived WebP
 * copies first — but only when both `public/mocks/derived/<stem>-760.webp` and
 * `…-1320.webp` exist; otherwise, and for every other image, the tag is
 * returned untouched. The `<img>` inside the wrapper is byte-identical to the
 * input. `<prefix>` is whatever precedes `/mocks/` (the site base, already
 * applied by rehype-base), never assumed.
 * @param {string} imgTag
 * @param {FigureOptions} [options]
 * @returns {string}
 */
export function pictureTag(imgTag, { exists = publicFileExists } = {}) {
  const src = RAW_SRC.exec(imgTag);
  const srcset = webpSrcset(src?.[1] ?? src?.[2] ?? src?.[3], exists);
  if (!srcset) return imgTag;
  return `<picture><source type="image/webp" srcset="${srcset}" sizes="${SIZES}">${imgTag}</picture>`;
}

/**
 * Gives a raw `<img …>` tag string the caption as `alt` when its own alt is a
 * placeholder (see `isPlaceholderAlt`); a written alt is kept as is.
 * @param {string} tag
 * @param {string | undefined} caption
 * @returns {string}
 */
export function captionAltTag(tag, caption) {
  if (!caption) return tag;
  const alt = RAW_ALT.exec(tag);
  const src = RAW_SRC.exec(tag);
  const current = alt ? (alt[1] ?? alt[2] ?? alt[3] ?? '') : undefined;
  if (!isPlaceholderAlt(current, src?.[1] ?? src?.[2] ?? src?.[3])) return tag;
  const attr = ` alt="${caption.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;')}"`;
  if (alt) return tag.replace(RAW_ALT, attr);
  return tag.replace(/^<img\b/i, `<img${attr}`);
}

/**
 * @param {HastNode} node
 * @returns {boolean}
 */
function isElementImg(node) {
  return node.type === 'element' && node.tagName === 'img';
}

/**
 * Returns the image node of a paragraph that contains nothing but one `<img>`
 * (whitespace allowed), or undefined.
 * @param {HastNode} node
 * @returns {HastNode | undefined}
 */
function soleImageOf(node) {
  if (node.type !== 'element' || node.tagName !== 'p') return undefined;
  const meaningful = (node.children ?? []).filter(
    (child) => !(child.type === 'text' && (child.value ?? '').trim() === ''),
  );
  return meaningful.length === 1 && isElementImg(meaningful[0]) ? meaningful[0] : undefined;
}

/**
 * Builds the `<figure>` wrapper around an image node.
 * @param {HastNode} image raw `<img>` string node, `img` element, or the `picture` around one
 * @param {string | undefined} caption
 * @returns {HastNode}
 */
function figureFor(image, caption) {
  /** @type {HastNode[]} */
  const children = [image];
  if (caption) {
    children.push({
      type: 'element',
      tagName: 'figcaption',
      properties: {},
      children: [{ type: 'text', value: caption }],
    });
  }
  return { type: 'element', tagName: 'figure', properties: { className: ['figure'] }, children };
}

/**
 * The element-path twin of `pictureTag`: wraps an `img` element whose `src` is
 * a mock screenshot with both derived copies present in a `picture` element
 * (`source` first, the same `img` node second); any other image is returned as
 * is. Kept minimal on purpose: no markdown `![]()` image in `content/` points at
 * `/mocks/` today — the gist's screenshots arrive as raw HTML — so this path is
 * covered by unit tests only.
 * @param {HastNode} image `img` element
 * @param {Exists} exists
 * @returns {HastNode}
 */
function pictureElement(image, exists) {
  const src = image.properties?.src;
  const srcset = webpSrcset(typeof src === 'string' ? src : undefined, exists);
  if (!srcset) return image;
  return {
    type: 'element',
    tagName: 'picture',
    properties: {},
    children: [
      { type: 'element', tagName: 'source', properties: { type: 'image/webp', srcSet: srcset, sizes: SIZES }, children: [] },
      image,
    ],
  };
}

/**
 * Rewrites the top-level children of `tree` in place. Exported for tests.
 * @param {HastNode} tree
 * @param {FigureOptions} [options]
 * @returns {number} number of figures created
 */
export function wrapFigures(tree, { exists = publicFileExists } = {}) {
  const children = tree.children ?? [];
  /** @type {string | undefined} */
  let caption;
  let count = 0;

  for (let i = 0; i < children.length; i++) {
    const node = children[i];

    if (node.type === 'element' && node.tagName) {
      if (CAPTION_TAGS.has(node.tagName)) {
        caption = textOf(node).trim() || undefined;
        continue;
      }
      if (SECTION_TAGS.has(node.tagName)) {
        caption = undefined;
        continue;
      }
    }

    // The first figure on the page is the likely LCP element: load it eagerly.
    const eager = count === 0;

    if (node.type === 'raw' && typeof node.value === 'string' && RAW_IMG_BLOCK.test(node.value)) {
      const img = captionAltTag(lazyImgTag(node.value.trim(), { eager }), caption);
      children[i] = figureFor({ type: 'raw', value: pictureTag(img, { exists }) }, caption);
      count++;
      continue;
    }

    const image = soleImageOf(node);
    if (image) {
      image.properties = eager
        ? { decoding: 'async', ...image.properties, loading: 'eager', fetchPriority: 'high' }
        : { loading: 'lazy', decoding: 'async', ...image.properties };
      const { alt, src } = image.properties;
      if (caption && isPlaceholderAlt(typeof alt === 'string' ? alt : undefined, typeof src === 'string' ? src : undefined)) {
        image.properties.alt = caption;
      }
      children[i] = figureFor(pictureElement(image, exists), caption);
      count++;
    }
  }

  return count;
}

/**
 * @param {FigureOptions} [options] `exists` defaults to checking `public/` under the cwd.
 */
export default function rehypeFigures(options = {}) {
  return (/** @type {HastNode} */ tree) => {
    wrapFigures(tree, options);
  };
}
