import { SITE } from './site.ts';

/**
 * Canonical URL for a page: the pathname (base included, as `Astro.url.pathname` gives it)
 * resolved against `site`, in the one form GitHub Pages serves without a redirect —
 * a trailing slash for pages, none for files.
 *
 *   canonicalUrl('/prd/sample', site)   → 'https://burkeholland.github.io/prd/sample/'
 *   canonicalUrl('/prd/sample/', site)  → 'https://burkeholland.github.io/prd/sample/'
 *   canonicalUrl('/prd', site)          → 'https://burkeholland.github.io/prd/'
 *   canonicalUrl('/prd/raw/x.md', site) → 'https://burkeholland.github.io/prd/raw/x.md'
 */
export function canonicalUrl(pathname: string, site: URL | string): string {
  const trimmed = pathname.replace(/\/+$/, '');
  const lastSegment = trimmed.slice(trimmed.lastIndexOf('/') + 1);
  const isFile = lastSegment.includes('.');
  const path = isFile ? trimmed : `${trimmed}/`;
  return new URL(path, site).href;
}

/** The site-wide social preview image (public/og.png, generated by scripts/make-og.mjs). */
export const OG_IMAGE = {
  path: '/og.png',
  width: 1200,
  height: 630,
  alt: 'PRD Field Guide — write a PRD an agent can build',
} as const;

/** One social preview card: the PNG under public/ (base-less path) and the copy drawn on it. */
export interface SocialCard {
  readonly file: string;
  readonly title: string;
  readonly subtitle: string;
  /** `og:image:alt`. */
  readonly alt: string;
}

function pageCard(file: string, title: string, subtitle: string): SocialCard {
  return { file, title, subtitle, alt: `${title} — ${SITE.name}` };
}

/**
 * The card per route (all `OG_IMAGE.width`×`OG_IMAGE.height`). scripts/make-og.mjs renders every
 * entry to `public` + `file`: the home card exactly as `public/og.png` always was, the page cards
 * with the site name as an eyebrow line over the page title. Keys are base-less routes in their
 * canonical (trailing-slash) form; `socialCard()` does the lookup.
 */
export const SOCIAL_CARDS = {
  '/': { file: OG_IMAGE.path, title: SITE.name, subtitle: SITE.tagline, alt: OG_IMAGE.alt },
  '/sample/': pageCard(
    '/og/sample.png',
    'The sample PRD',
    'Build The Urlist — the complete instruction Burke Holland handed to a coding agent: mocks, stack, routes, exact copy, tests, and a definition of done.',
  ),
  '/guide/': pageCard(
    '/og/guide.png',
    'How to write one',
    'Seven habits that separate a PRD an agent can execute from one it has to guess at.',
  ),
  '/walkthrough/': pageCard(
    '/og/walkthrough.png',
    'Worked example',
    'The sample PRD, section by section: what each part does, why it works, and what to steal.',
  ),
  '/history/': pageCard(
    '/og/history.png',
    'How it evolved',
    'Sixteen revisions over three weeks: what grew, what was rewritten, and when.',
  ),
  '/template/': pageCard(
    '/og/template.png',
    'Template',
    'The skeleton of a PRD an agent can build from — copy it, keep the order, fill every section.',
  ),
} as const satisfies Record<string, SocialCard>;

/**
 * The social card for a page: `pathname` as `Astro.url.pathname` gives it (base included), `base`
 * as `import.meta.env.BASE_URL` gives it (with or without a trailing slash). Anything that is not
 * one of the six pages — the 404 page, `/history/<n>/`, an unknown path — gets the home card.
 *
 *   socialCard('/prd/history/', '/prd')  → SOCIAL_CARDS['/history/']
 *   socialCard('/prd/history', '/prd')   → SOCIAL_CARDS['/history/']
 *   socialCard('/prd', '/prd')           → SOCIAL_CARDS['/']
 *   socialCard('/prd/history/3/', '/prd') → SOCIAL_CARDS['/']
 *   socialCard('/guide/', '/')           → SOCIAL_CARDS['/guide/']
 */
export function socialCard(pathname: string, base: string): (typeof SOCIAL_CARDS)[keyof typeof SOCIAL_CARDS] {
  const prefix = base.replace(/\/+$/, '');
  const inBase = prefix !== '' && (pathname === prefix || pathname.startsWith(`${prefix}/`));
  const inner = (inBase ? pathname.slice(prefix.length) : pathname).replace(/^\/+|\/+$/g, '');
  const route = inner === '' ? '/' : `/${inner}/`;
  return route in SOCIAL_CARDS ? SOCIAL_CARDS[route as keyof typeof SOCIAL_CARDS] : SOCIAL_CARDS['/'];
}
