/**
 * Canonical URL for a page: the pathname (base included, as `Astro.url.pathname` gives it)
 * resolved against `site`, in the one form GitHub Pages serves without a redirect —
 * a trailing slash for pages, none for files.
 *
 *   canonicalUrl('/prd/sample', site)   → 'https://burkeholland.github.io/prd/sample/'
 *   canonicalUrl('/prd/sample/', site)  → 'https://burkeholland.github.io/prd/sample/'
 *   canonicalUrl('/prd', site)          → 'https://burkeholland.github.io/prd/'
 *   canonicalUrl('/prd/raw/x.md', site) → 'https://burkeholland.github.io/prd/raw/x.md'
 */
export function canonicalUrl(pathname: string, site: URL | string): string {
  const trimmed = pathname.replace(/\/+$/, '');
  const lastSegment = trimmed.slice(trimmed.lastIndexOf('/') + 1);
  const isFile = lastSegment.includes('.');
  const path = isFile ? trimmed : `${trimmed}/`;
  return new URL(path, site).href;
}

/** The social preview image (public/og.png, generated by scripts/make-og.mjs). */
export const OG_IMAGE = {
  path: '/og.png',
  width: 1200,
  height: 630,
  alt: 'PRD Field Guide — write a PRD an agent can build',
} as const;
